services:
  acquirer-bank:
    build:
      context: ./acquirer-bank
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  payment-provider-frontend:
    build:
      context: ./payment-provider/payment-provider-frontend
      dockerfile: Dockerfile
    ports:
      - "4300:80"
    depends_on:
      - payment-provider-backend

  payment-provider-backend:
    build:
      context: ./payment-provider/payment-provider-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  rent-an-auto-backend:
    build:
      context: ./rent-an-auto/rent-an-auto-backend
      dockerfile: Dockerfile
    volumes:
      - ./rent-an-auto/rent-an-auto-backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  rent-an-auto-frontend:
    build:
      context: ./rent-an-auto/rent-an-auto-frontend
      dockerfile: Dockerfile
    ports:
      - "4301:80"
    depends_on:
      - rent-an-auto-backend

  mysql:
    image: mysql:8.0
    container_name: payment_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
